# Generated by Django 3.2.5 on 2021-08-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('FM', 'формируется'), ('STP', 'отправлен в обработку'), ('PRD', 'обрабатывается'), ('PD', 'оплачен'), ('RDY', 'готов к выдачe'), ('CNC', 'отменён')], default='FM', max_length=3, verbose_name='статус'),
        ),
    ]
