# Generated by Django 3.2.5 on 2021-09-01 19:01

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orderitem',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
