# Generated by Django 3.2.5 on 2021-09-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0004_alter_orderitem_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
