# Generated by Django 3.2.5 on 2021-08-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='add_delete',
            new_name='add_datetime',
        ),
    ]
